# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore,QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(346, 208)
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.keyEdit = QtWidgets.QLineEdit(Dialog)
        self.keyEdit.setText("")
        self.keyEdit.setObjectName("keyEdit")
        self.horizontalLayout_2.addWidget(self.keyEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.idEdit = QtWidgets.QLineEdit(Dialog)
        self.idEdit.setText("")
        self.idEdit.setObjectName("idEdit")
        self.horizontalLayout_3.addWidget(self.idEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.dnumBtn = QtWidgets.QPushButton(Dialog)
        self.dnumBtn.setObjectName("dnumBtn")
        self.horizontalLayout_4.addWidget(self.dnumBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.howBtn = QtWidgets.QPushButton(Dialog)
        self.howBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.howBtn.setObjectName("howBtn")
        self.horizontalLayout_4.addWidget(self.howBtn)
        self.configBtn = QtWidgets.QPushButton(Dialog)
        self.configBtn.setEnabled(False)
        self.configBtn.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.configBtn.setObjectName("configBtn")
        self.horizontalLayout_4.addWidget(self.configBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "配置"))
        self.groupBox.setTitle(_translate("Dialog", "准确填写"))
        self.label.setText(_translate("Dialog", "remix_userkey"))
        self.keyEdit.setPlaceholderText(_translate("Dialog", "remix_userkey"))
        self.label_2.setText(_translate("Dialog", "remix_userid "))
        self.idEdit.setPlaceholderText(_translate("id", "remix_userid"))
        self.dnumBtn.setText(_translate("Dialog","余量查询"))
        self.howBtn.setText(_translate("Dialog", "如何获取"))
        self.configBtn.setText(_translate("Dialog", "确定"))
