# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'disclaimerWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Disclaimers(object):
    def setupUi(self, Disclaimers):
        Disclaimers.setObjectName("Disclaimers")
        Disclaimers.resize(850, 400)
        icon = QtGui.QIcon()
        self.label_2 = QtWidgets.QLabel(Disclaimers)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 850, 500))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Disclaimers)
        QtCore.QMetaObject.connectSlotsByName(Disclaimers)

    def retranslateUi(self, Disclaimers):
        _translate = QtCore.QCoreApplication.translate
        Disclaimers.setWindowTitle(_translate("Disclaimers", "olib免责声明"))
        self.label_2.setText(_translate("Disclaimers",
"亲爱的小伙伴你好，在您使用本工具时，应当且必须认真阅读并遵守以下内容：\n"
"1.本软件不从事任何商业行为，不涉及任何付费服务，所有人均可免费使用。\n"
"2.本工具为独立运行软件,资源聚合自互联网,未对任何互联网资源提供存储。\n"
"3.本工具为开源软件,不保证所有功能完全有效，您可自由获取软件源码。\n"
"4.本工具具体使用情况与您当前网络环境有关。\n"
"5.本工具仅限于学习、研究等正常使用，软件运行过程中，除运行者外，他人无法干预。\n"
"6.本工具不收集任何关于您的信息，包括且不仅限于设备信息\n"
"7.请您遵守所在地的法律法规，切勿使用本工具进行违法违规行为，您应自行承担使用后果。\n"))
from .disclaimers_ui_res import qInitResources
