# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DonatePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets,QtGui
from PyQt5.QtWidgets import QVBoxLayout
class Ui_Donate_Page(object):
    def setupUi(self, Donate_Page):
        Donate_Page.setObjectName("Donate_Page")
        Donate_Page.resize(440, 420)
        Donate_Page.setStyleSheet("background:rgb(255, 255, 255)")
        layout = QVBoxLayout(Donate_Page)
        layout.setAlignment(QtCore.Qt.AlignCenter)

        self.label = QtWidgets.QLabel()
        pixmap = QtGui.QPixmap(
            ":/pic/picRes/donate.png")  # 使用你的图片路径
        self.label.setFixedSize(300,300)
        pixmap = pixmap.scaled(self.label.size())  # 平铺图片

        self.label.setPixmap(pixmap)
        self.label_2 = QtWidgets.QLabel()
        self.label_2.setStyleSheet("QLabel{\n""font-size:18px;\n""}")
        self.label_2.setObjectName("label_2")
        self.label_2.setWordWrap(True)
        layout.addWidget(self.label)
        layout.addWidget(self.label_2)
        self.retranslateUi(Donate_Page)
        QtCore.QMetaObject.connectSlotsByName(Donate_Page)

    def retranslateUi(self, Donate_Page):
        _translate = QtCore.QCoreApplication.translate
        Donate_Page.setWindowTitle(_translate("Donate_Page", "支持"))
        self.label_2.setText(_translate("Donate_Page","您的每一分赞赏，都能让项目有更好的运行环境~\n致敬每一位爱读书的人，希望能帮助到您！"))
        self.label_2.setWordWrap(True)
from .donate_ui_pic import qInitResources
