from PyQt5 import QtCore, QtGui, QtWidgets
import qtawesome as qta
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(875, 841)
        icon = QtGui.QIcon(qta.icon('ri.book-read-line'))
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bookEdit = QtWidgets.QLineEdit(self.tab)
        self.bookEdit.setText("")
        self.bookEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.bookEdit.setObjectName("bookEdit")
        self.horizontalLayout.addWidget(self.bookEdit)
        self.modeBox = QtWidgets.QComboBox(self.tab)
        self.modeBox.setObjectName("modeBox")
        self.horizontalLayout.addWidget(self.modeBox)
        self.brBox = QtWidgets.QComboBox(self.tab)
        self.brBox.setObjectName("brBox")
        self.horizontalLayout.addWidget(self.brBox)

        self.accurateCheck = QtWidgets.QCheckBox(self.tab)  # 精准搜索
        self.accurateCheck.setChecked(False)
        # self.accurateCheck.setDisabled(True)
        # self.accurateCheck.setToolTip("精准搜索暂不可用")
        self.accurateCheck.setObjectName("accurateCheck")
        self.horizontalLayout.addWidget(self.accurateCheck)

        self.queryBtn = QtWidgets.QPushButton(self.tab)
        self.queryBtn.setObjectName("queryBtn")
        self.queryBtn.setToolTip("点击或者按下回车键都可搜索")
        self.horizontalLayout.addWidget(self.queryBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.proBtn = QtWidgets.QPushButton(self.tab)
        self.proBtn.setObjectName("proBtn")
        self.horizontalLayout_4.addWidget(self.proBtn)
        self.preBtn = QtWidgets.QPushButton(self.tab)
        self.preBtn.setObjectName("preBtn")
        self.horizontalLayout_4.addWidget(self.preBtn)
        self.pageLabel = QtWidgets.QLabel(self.tab)
        self.pageLabel.setObjectName("pageLabel")
        self.pageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.horizontalLayout_4.addWidget(self.pageLabel)
        self.nextBtn = QtWidgets.QPushButton(self.tab)
        self.nextBtn.setObjectName("nextBtn")
        self.horizontalLayout_4.addWidget(self.nextBtn)

        self.donateBtn = QtWidgets.QPushButton(self.tab)
        self.donateBtn.setObjectName("donateBtn")
        self.horizontalLayout_4.addWidget(self.donateBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.skipCheck = QtWidgets.QCheckBox(self.groupBox)
        self.skipCheck.setChecked(True)
        self.skipCheck.setObjectName("skipCheck")
        self.horizontalLayout_6.addWidget(self.skipCheck)
        self.fontComboBox = QtWidgets.QFontComboBox()
        self.horizontalLayout_6.addWidget(self.skipCheck)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pathLB = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathLB.sizePolicy().hasHeightForWidth())
        self.pathLB.setSizePolicy(sizePolicy)
        self.pathLB.setObjectName("pathLB")
        self.horizontalLayout_7.addWidget(self.pathLB)
        self.pathBtn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathBtn.sizePolicy().hasHeightForWidth())
        self.pathBtn.setSizePolicy(sizePolicy)
        self.pathBtn.setObjectName("pathBtn")
        self.horizontalLayout_7.addWidget(self.pathBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addWidget(self.groupBox)

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.gitBtn = QtWidgets.QPushButton(self.tab)
        self.gitBtn.setObjectName("gitBtn")
        self.horizontalLayout_2.addWidget(self.gitBtn)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.disclaimerBtn = QtWidgets.QPushButton(self.tab)
        self.disclaimerBtn.setObjectName("disclaimerBtn")
        self.horizontalLayout_2.addWidget(self.disclaimerBtn)



        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab, "")

        self.tabDownload = QtWidgets.QWidget()
        self.tabDownload.setObjectName("tabDownload")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabDownload)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidgetDownload = QtWidgets.QTableWidget(self.tabDownload)
        self.tableWidgetDownload.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.tableWidgetDownload.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.tableWidgetDownload.setColumnCount(3)
        self.tableWidgetDownload.setObjectName("tableWidgetDownload")
        self.tableWidgetDownload.setRowCount(0)
        #动态缩放
        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        #不允许编辑
        self.tableWidget.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDownload.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDownload.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDownload.setHorizontalHeaderItem(2, item)
        self.verticalLayout_3.addWidget(self.tableWidgetDownload)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tabDownload, "")


        self.verticalLayout_5.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 875, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.exitBtn = QtWidgets.QAction(MainWindow)
        self.exitBtn.setCheckable(False)
        self.exitBtn.setObjectName("exitBtn")
        self.aboutAction = QtWidgets.QAction(MainWindow)
        self.aboutAction.setObjectName("aboutAction")
        self.websiteAction = QtWidgets.QAction(MainWindow)
        self.websiteAction.setObjectName("websiteAction")
        self.configAction = QtWidgets.QAction(MainWindow)
        self.configAction.setObjectName("configAction")
        self.helpAction = QtWidgets.QAction(MainWindow)
        self.helpAction.setObjectName("helpAction")
        self.menu.addAction(self.configAction)
        self.menu_2.addAction(self.exitBtn)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.helpAction)
        self.menu_3.addAction(self.aboutAction)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.websiteAction)
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.brBox.setCurrentIndex(-1)
        # self.brBox.setDisabled(True)#禁用扩展名
        self.modeBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OLib-开源图书1.0.9"))
        self.bookEdit.setPlaceholderText(_translate("MainWindow", "请输入书籍名或ISBN号"))
        self.queryBtn.setText(_translate("MainWindow", "查询"))
        self.tableWidget.setSortingEnabled(False)
        self.proBtn.setText(_translate("MainWindow", "高级"))
        self.preBtn.setText(_translate("MainWindow", "上一页"))
        self.nextBtn.setText(_translate("MainWindow", "下一页"))
        self.donateBtn.setToolTip(_translate("MainWindow", "您的赞赏，会让软件变得更好~"))
        self.donateBtn.setText(_translate("MainWindow", "赞赏"))
        self.groupBox.setTitle(_translate("MainWindow", "高级"))
        self.skipCheck.setText(_translate("MainWindow", "跳过存在文件"))
        self.accurateCheck.setText(_translate("MainWindow", "精准搜索"))
        self.pathBtn.setText(_translate("MainWindow", "下载目录"))
        self.label_3.setText(_translate("MainWindow", "感谢您的使用"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "书籍详情"))
        item = self.tableWidgetDownload.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "书名"))
        item = self.tableWidgetDownload.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "下载进度"))
        item = self.tableWidgetDownload.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "下载速度"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDownload), _translate("MainWindow", "下载"))
        self.menu.setTitle(_translate("MainWindow", "配置"))
        self.menu_2.setTitle(_translate("MainWindow", "文件"))
        self.menu_3.setTitle(_translate("MainWindow", "关于"))
        self.exitBtn.setText(_translate("MainWindow", "退出"))
        self.aboutAction.setText(_translate("MainWindow", "关于作者"))
        self.websiteAction.setText(_translate("MainWindow", "访问导航网站"))
        self.configAction.setText(_translate("MainWindow", "设置"))
        self.helpAction.setText(_translate("MainWindow", "帮助"))
